/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.website.mapper;

import com.hpb.bc.entity.CoinConfig;
import com.hpb.bc.example.CoinConfigExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface CoinConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    long countByExample(CoinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    int deleteByExample(CoinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    int insert(CoinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    int insertSelective(CoinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    List<CoinConfig> selectByExample(CoinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    CoinConfig selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CoinConfig record, @Param("example") CoinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CoinConfig record, @Param("example") CoinConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CoinConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CoinConfig record);
    List<CoinConfig> selectByStatus(String status);
    List<CoinConfig> selectByStatusAndType(Map<String, String> param);
}