/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.website.mapper;

import com.hpb.bc.entity.HpbInstantPrice;
import com.hpb.bc.example.HpbInstantPriceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HpbInstantPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    long countByExample(HpbInstantPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    int deleteByExample(HpbInstantPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    int insert(HpbInstantPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    int insertSelective(HpbInstantPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    List<HpbInstantPrice> selectByExample(HpbInstantPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    HpbInstantPrice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpbInstantPrice record, @Param("example") HpbInstantPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpbInstantPrice record, @Param("example") HpbInstantPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpbInstantPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpbInstantPrice record);
    HpbInstantPrice selectByCoinSymbol(String symbol);
}