/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.website.mapper;

import com.hpb.bc.entity.IssueVote;
import com.hpb.bc.example.IssueVoteExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IssueVoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    long countByExample(IssueVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    int deleteByExample(IssueVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    int insert(IssueVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    int insertSelective(IssueVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    List<IssueVote> selectByExample(IssueVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    IssueVote selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IssueVote record, @Param("example") IssueVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IssueVote record, @Param("example") IssueVoteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IssueVote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IssueVote record);
    List<IssueVote> queryInitIssueVotes();
    List<IssueVote> queryEndIssueVotes();
    IssueVote queryByNo(String no);
    List<IssueVote> queryAll();
}