/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.website.mapper;

import com.hpb.bc.entity.IssueVoteDetail;
import com.hpb.bc.example.IssueVoteDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface IssueVoteDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    long countByExample(IssueVoteDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    int deleteByExample(IssueVoteDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    int insert(IssueVoteDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    int insertSelective(IssueVoteDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    List<IssueVoteDetail> selectByExample(IssueVoteDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    IssueVoteDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IssueVoteDetail record, @Param("example") IssueVoteDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IssueVoteDetail record, @Param("example") IssueVoteDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IssueVoteDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IssueVoteDetail record);
    IssueVoteDetail queryByNoAddrOptionKey(Map<String, String> param);
}