package com.hpb.bc.website.mapper;

import com.hpb.bc.entity.RedPacketSend;
import com.hpb.bc.example.RedPacketSendExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface RedPacketSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    long countByExample(RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int deleteByExample(RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int insert(RedPacketSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int insertSelective(RedPacketSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    List<RedPacketSend> selectByExample(RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    RedPacketSend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RedPacketSend record, @Param("example") RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RedPacketSend record, @Param("example") RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RedPacketSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RedPacketSend record);
    int insertBatch(List<RedPacketSend> records);

    RedPacketSend selectTokenId(Map<String, String> param);
    int updateUsedWithRefund(Map<String, String> param);
    List<RedPacketSend> list(String redPacketNo);
    RedPacketSend selectNotIntokenIds(Map<String, Object> param);
    RedPacketSend querySendWithtokenId(Map<String, Object> param);
}