/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.website.mapper;

import com.hpb.bc.entity.RedPacketSend;
import com.hpb.bc.example.RedPacketSendExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface RedPacketSendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    long countByExample(RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int deleteByExample(RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int insert(RedPacketSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int insertSelective(RedPacketSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    List<RedPacketSend> selectByExample(RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    RedPacketSend selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RedPacketSend record, @Param("example") RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RedPacketSend record, @Param("example") RedPacketSendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RedPacketSend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_send
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RedPacketSend record);
    int insertBatch(List<RedPacketSend> records);

    RedPacketSend selectTokenId(Map<String, String> param);
    int updateUsedWithRefund(Map<String, String> param);
    List<RedPacketSend> list(String redPacketNo);
    RedPacketSend selectNotIntokenIds(Map<String, Object> param);
    RedPacketSend querySendWithtokenId(Map<String, Object> param);
}