/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.website.mapper;

import com.hpb.bc.entity.RedPacketConfig;
import com.hpb.bc.example.RedPacketConfigExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RedPacketConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    long countByExample(RedPacketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    int deleteByExample(RedPacketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    int insert(RedPacketConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    int insertSelective(RedPacketConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    List<RedPacketConfig> selectByExample(RedPacketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    RedPacketConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RedPacketConfig record, @Param("example") RedPacketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RedPacketConfig record, @Param("example") RedPacketConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RedPacketConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RedPacketConfig record);
    RedPacketConfig selectByEnterType(String enterType);
}