package com.hpb.bc.website.mapper;

import com.hpb.bc.entity.RedPacketRefund;
import com.hpb.bc.example.RedPacketRefundExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RedPacketRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    long countByExample(RedPacketRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    int deleteByExample(RedPacketRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    int insert(RedPacketRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    int insertSelective(RedPacketRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    List<RedPacketRefund> selectByExample(RedPacketRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    RedPacketRefund selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RedPacketRefund record, @Param("example") RedPacketRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RedPacketRefund record, @Param("example") RedPacketRefundExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RedPacketRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_refund
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RedPacketRefund record);
}