/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.website.mapper;

import com.hpb.bc.entity.RedPacket;
import com.hpb.bc.example.RedPacketExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface RedPacketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    long countByExample(RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    int deleteByExample(RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    int insert(RedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    int insertSelective(RedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    List<RedPacket> selectByExample(RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    RedPacket selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RedPacket record, @Param("example") RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RedPacket record, @Param("example") RedPacketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RedPacket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RedPacket record);
    RedPacket selectByRedPacketNoAndIsOver(Map<String, String> param);
    int updateIsOver(Map<String, String> param);
    RedPacket queryByRedPacketNo(String redPacketNo);
    int updateWithParam(Map<String, Object> param);
}