package com.hpb.bc.example;

import java.util.ArrayList;
import java.util.List;

public class HpbDataDicExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public HpbDataDicExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoIsNull() {
            addCriterion("data_type_no is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoIsNotNull() {
            addCriterion("data_type_no is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoEqualTo(Integer value) {
            addCriterion("data_type_no =", value, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoNotEqualTo(Integer value) {
            addCriterion("data_type_no <>", value, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoGreaterThan(Integer value) {
            addCriterion("data_type_no >", value, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("data_type_no >=", value, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoLessThan(Integer value) {
            addCriterion("data_type_no <", value, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoLessThanOrEqualTo(Integer value) {
            addCriterion("data_type_no <=", value, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoIn(List<Integer> values) {
            addCriterion("data_type_no in", values, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoNotIn(List<Integer> values) {
            addCriterion("data_type_no not in", values, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoBetween(Integer value1, Integer value2) {
            addCriterion("data_type_no between", value1, value2, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNoNotBetween(Integer value1, Integer value2) {
            addCriterion("data_type_no not between", value1, value2, "dataTypeNo");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameIsNull() {
            addCriterion("data_type_name is null");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameIsNotNull() {
            addCriterion("data_type_name is not null");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameEqualTo(String value) {
            addCriterion("data_type_name =", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameNotEqualTo(String value) {
            addCriterion("data_type_name <>", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameGreaterThan(String value) {
            addCriterion("data_type_name >", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameGreaterThanOrEqualTo(String value) {
            addCriterion("data_type_name >=", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameLessThan(String value) {
            addCriterion("data_type_name <", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameLessThanOrEqualTo(String value) {
            addCriterion("data_type_name <=", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameLike(String value) {
            addCriterion("data_type_name like", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameNotLike(String value) {
            addCriterion("data_type_name not like", value, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameIn(List<String> values) {
            addCriterion("data_type_name in", values, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameNotIn(List<String> values) {
            addCriterion("data_type_name not in", values, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameBetween(String value1, String value2) {
            addCriterion("data_type_name between", value1, value2, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataTypeNameNotBetween(String value1, String value2) {
            addCriterion("data_type_name not between", value1, value2, "dataTypeName");
            return (Criteria) this;
        }

        public Criteria andDataNoIsNull() {
            addCriterion("data_no is null");
            return (Criteria) this;
        }

        public Criteria andDataNoIsNotNull() {
            addCriterion("data_no is not null");
            return (Criteria) this;
        }

        public Criteria andDataNoEqualTo(String value) {
            addCriterion("data_no =", value, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoNotEqualTo(String value) {
            addCriterion("data_no <>", value, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoGreaterThan(String value) {
            addCriterion("data_no >", value, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoGreaterThanOrEqualTo(String value) {
            addCriterion("data_no >=", value, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoLessThan(String value) {
            addCriterion("data_no <", value, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoLessThanOrEqualTo(String value) {
            addCriterion("data_no <=", value, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoLike(String value) {
            addCriterion("data_no like", value, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoNotLike(String value) {
            addCriterion("data_no not like", value, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoIn(List<String> values) {
            addCriterion("data_no in", values, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoNotIn(List<String> values) {
            addCriterion("data_no not in", values, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoBetween(String value1, String value2) {
            addCriterion("data_no between", value1, value2, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNoNotBetween(String value1, String value2) {
            addCriterion("data_no not between", value1, value2, "dataNo");
            return (Criteria) this;
        }

        public Criteria andDataNameIsNull() {
            addCriterion("data_name is null");
            return (Criteria) this;
        }

        public Criteria andDataNameIsNotNull() {
            addCriterion("data_name is not null");
            return (Criteria) this;
        }

        public Criteria andDataNameEqualTo(String value) {
            addCriterion("data_name =", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotEqualTo(String value) {
            addCriterion("data_name <>", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameGreaterThan(String value) {
            addCriterion("data_name >", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameGreaterThanOrEqualTo(String value) {
            addCriterion("data_name >=", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameLessThan(String value) {
            addCriterion("data_name <", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameLessThanOrEqualTo(String value) {
            addCriterion("data_name <=", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameLike(String value) {
            addCriterion("data_name like", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotLike(String value) {
            addCriterion("data_name not like", value, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameIn(List<String> values) {
            addCriterion("data_name in", values, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotIn(List<String> values) {
            addCriterion("data_name not in", values, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameBetween(String value1, String value2) {
            addCriterion("data_name between", value1, value2, "dataName");
            return (Criteria) this;
        }

        public Criteria andDataNameNotBetween(String value1, String value2) {
            addCriterion("data_name not between", value1, value2, "dataName");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andDataNoLenIsNull() {
            addCriterion("data_no_len is null");
            return (Criteria) this;
        }

        public Criteria andDataNoLenIsNotNull() {
            addCriterion("data_no_len is not null");
            return (Criteria) this;
        }

        public Criteria andDataNoLenEqualTo(Integer value) {
            addCriterion("data_no_len =", value, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andDataNoLenNotEqualTo(Integer value) {
            addCriterion("data_no_len <>", value, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andDataNoLenGreaterThan(Integer value) {
            addCriterion("data_no_len >", value, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andDataNoLenGreaterThanOrEqualTo(Integer value) {
            addCriterion("data_no_len >=", value, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andDataNoLenLessThan(Integer value) {
            addCriterion("data_no_len <", value, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andDataNoLenLessThanOrEqualTo(Integer value) {
            addCriterion("data_no_len <=", value, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andDataNoLenIn(List<Integer> values) {
            addCriterion("data_no_len in", values, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andDataNoLenNotIn(List<Integer> values) {
            addCriterion("data_no_len not in", values, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andDataNoLenBetween(Integer value1, Integer value2) {
            addCriterion("data_no_len between", value1, value2, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andDataNoLenNotBetween(Integer value1, Integer value2) {
            addCriterion("data_no_len not between", value1, value2, "dataNoLen");
            return (Criteria) this;
        }

        public Criteria andLimitFlagIsNull() {
            addCriterion("limit_flag is null");
            return (Criteria) this;
        }

        public Criteria andLimitFlagIsNotNull() {
            addCriterion("limit_flag is not null");
            return (Criteria) this;
        }

        public Criteria andLimitFlagEqualTo(String value) {
            addCriterion("limit_flag =", value, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagNotEqualTo(String value) {
            addCriterion("limit_flag <>", value, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagGreaterThan(String value) {
            addCriterion("limit_flag >", value, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagGreaterThanOrEqualTo(String value) {
            addCriterion("limit_flag >=", value, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagLessThan(String value) {
            addCriterion("limit_flag <", value, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagLessThanOrEqualTo(String value) {
            addCriterion("limit_flag <=", value, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagLike(String value) {
            addCriterion("limit_flag like", value, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagNotLike(String value) {
            addCriterion("limit_flag not like", value, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagIn(List<String> values) {
            addCriterion("limit_flag in", values, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagNotIn(List<String> values) {
            addCriterion("limit_flag not in", values, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagBetween(String value1, String value2) {
            addCriterion("limit_flag between", value1, value2, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andLimitFlagNotBetween(String value1, String value2) {
            addCriterion("limit_flag not between", value1, value2, "limitFlag");
            return (Criteria) this;
        }

        public Criteria andHighLimitIsNull() {
            addCriterion("high_limit is null");
            return (Criteria) this;
        }

        public Criteria andHighLimitIsNotNull() {
            addCriterion("high_limit is not null");
            return (Criteria) this;
        }

        public Criteria andHighLimitEqualTo(String value) {
            addCriterion("high_limit =", value, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitNotEqualTo(String value) {
            addCriterion("high_limit <>", value, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitGreaterThan(String value) {
            addCriterion("high_limit >", value, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitGreaterThanOrEqualTo(String value) {
            addCriterion("high_limit >=", value, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitLessThan(String value) {
            addCriterion("high_limit <", value, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitLessThanOrEqualTo(String value) {
            addCriterion("high_limit <=", value, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitLike(String value) {
            addCriterion("high_limit like", value, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitNotLike(String value) {
            addCriterion("high_limit not like", value, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitIn(List<String> values) {
            addCriterion("high_limit in", values, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitNotIn(List<String> values) {
            addCriterion("high_limit not in", values, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitBetween(String value1, String value2) {
            addCriterion("high_limit between", value1, value2, "highLimit");
            return (Criteria) this;
        }

        public Criteria andHighLimitNotBetween(String value1, String value2) {
            addCriterion("high_limit not between", value1, value2, "highLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitIsNull() {
            addCriterion("low_limit is null");
            return (Criteria) this;
        }

        public Criteria andLowLimitIsNotNull() {
            addCriterion("low_limit is not null");
            return (Criteria) this;
        }

        public Criteria andLowLimitEqualTo(String value) {
            addCriterion("low_limit =", value, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitNotEqualTo(String value) {
            addCriterion("low_limit <>", value, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitGreaterThan(String value) {
            addCriterion("low_limit >", value, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitGreaterThanOrEqualTo(String value) {
            addCriterion("low_limit >=", value, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitLessThan(String value) {
            addCriterion("low_limit <", value, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitLessThanOrEqualTo(String value) {
            addCriterion("low_limit <=", value, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitLike(String value) {
            addCriterion("low_limit like", value, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitNotLike(String value) {
            addCriterion("low_limit not like", value, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitIn(List<String> values) {
            addCriterion("low_limit in", values, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitNotIn(List<String> values) {
            addCriterion("low_limit not in", values, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitBetween(String value1, String value2) {
            addCriterion("low_limit between", value1, value2, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andLowLimitNotBetween(String value1, String value2) {
            addCriterion("low_limit not between", value1, value2, "lowLimit");
            return (Criteria) this;
        }

        public Criteria andEffectDateIsNull() {
            addCriterion("effect_date is null");
            return (Criteria) this;
        }

        public Criteria andEffectDateIsNotNull() {
            addCriterion("effect_date is not null");
            return (Criteria) this;
        }

        public Criteria andEffectDateEqualTo(Long value) {
            addCriterion("effect_date =", value, "effectDate");
            return (Criteria) this;
        }

        public Criteria andEffectDateNotEqualTo(Long value) {
            addCriterion("effect_date <>", value, "effectDate");
            return (Criteria) this;
        }

        public Criteria andEffectDateGreaterThan(Long value) {
            addCriterion("effect_date >", value, "effectDate");
            return (Criteria) this;
        }

        public Criteria andEffectDateGreaterThanOrEqualTo(Long value) {
            addCriterion("effect_date >=", value, "effectDate");
            return (Criteria) this;
        }

        public Criteria andEffectDateLessThan(Long value) {
            addCriterion("effect_date <", value, "effectDate");
            return (Criteria) this;
        }

        public Criteria andEffectDateLessThanOrEqualTo(Long value) {
            addCriterion("effect_date <=", value, "effectDate");
            return (Criteria) this;
        }

        public Criteria andEffectDateIn(List<Long> values) {
            addCriterion("effect_date in", values, "effectDate");
            return (Criteria) this;
        }

        public Criteria andEffectDateNotIn(List<Long> values) {
            addCriterion("effect_date not in", values, "effectDate");
            return (Criteria) this;
        }

        public Criteria andEffectDateBetween(Long value1, Long value2) {
            addCriterion("effect_date between", value1, value2, "effectDate");
            return (Criteria) this;
        }

        public Criteria andEffectDateNotBetween(Long value1, Long value2) {
            addCriterion("effect_date not between", value1, value2, "effectDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNull() {
            addCriterion("expire_date is null");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNotNull() {
            addCriterion("expire_date is not null");
            return (Criteria) this;
        }

        public Criteria andExpireDateEqualTo(Long value) {
            addCriterion("expire_date =", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotEqualTo(Long value) {
            addCriterion("expire_date <>", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThan(Long value) {
            addCriterion("expire_date >", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThanOrEqualTo(Long value) {
            addCriterion("expire_date >=", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThan(Long value) {
            addCriterion("expire_date <", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThanOrEqualTo(Long value) {
            addCriterion("expire_date <=", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateIn(List<Long> values) {
            addCriterion("expire_date in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotIn(List<Long> values) {
            addCriterion("expire_date not in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateBetween(Long value1, Long value2) {
            addCriterion("expire_date between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotBetween(Long value1, Long value2) {
            addCriterion("expire_date not between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Long value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Long value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Long value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Long value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Long value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Long> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Long> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Long value1, Long value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Long value1, Long value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andShowSeqIsNull() {
            addCriterion("show_seq is null");
            return (Criteria) this;
        }

        public Criteria andShowSeqIsNotNull() {
            addCriterion("show_seq is not null");
            return (Criteria) this;
        }

        public Criteria andShowSeqEqualTo(Integer value) {
            addCriterion("show_seq =", value, "showSeq");
            return (Criteria) this;
        }

        public Criteria andShowSeqNotEqualTo(Integer value) {
            addCriterion("show_seq <>", value, "showSeq");
            return (Criteria) this;
        }

        public Criteria andShowSeqGreaterThan(Integer value) {
            addCriterion("show_seq >", value, "showSeq");
            return (Criteria) this;
        }

        public Criteria andShowSeqGreaterThanOrEqualTo(Integer value) {
            addCriterion("show_seq >=", value, "showSeq");
            return (Criteria) this;
        }

        public Criteria andShowSeqLessThan(Integer value) {
            addCriterion("show_seq <", value, "showSeq");
            return (Criteria) this;
        }

        public Criteria andShowSeqLessThanOrEqualTo(Integer value) {
            addCriterion("show_seq <=", value, "showSeq");
            return (Criteria) this;
        }

        public Criteria andShowSeqIn(List<Integer> values) {
            addCriterion("show_seq in", values, "showSeq");
            return (Criteria) this;
        }

        public Criteria andShowSeqNotIn(List<Integer> values) {
            addCriterion("show_seq not in", values, "showSeq");
            return (Criteria) this;
        }

        public Criteria andShowSeqBetween(Integer value1, Integer value2) {
            addCriterion("show_seq between", value1, value2, "showSeq");
            return (Criteria) this;
        }

        public Criteria andShowSeqNotBetween(Integer value1, Integer value2) {
            addCriterion("show_seq not between", value1, value2, "showSeq");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Long value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Long value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Long value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Long value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Long value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Long> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Long> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Long value1, Long value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Long value1, Long value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpb_data_dic
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}