package com.hpb.bc.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HpbInstantPriceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public HpbInstantPriceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolIsNull() {
            addCriterion("coin_symbol is null");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolIsNotNull() {
            addCriterion("coin_symbol is not null");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolEqualTo(String value) {
            addCriterion("coin_symbol =", value, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolNotEqualTo(String value) {
            addCriterion("coin_symbol <>", value, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolGreaterThan(String value) {
            addCriterion("coin_symbol >", value, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolGreaterThanOrEqualTo(String value) {
            addCriterion("coin_symbol >=", value, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolLessThan(String value) {
            addCriterion("coin_symbol <", value, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolLessThanOrEqualTo(String value) {
            addCriterion("coin_symbol <=", value, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolLike(String value) {
            addCriterion("coin_symbol like", value, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolNotLike(String value) {
            addCriterion("coin_symbol not like", value, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolIn(List<String> values) {
            addCriterion("coin_symbol in", values, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolNotIn(List<String> values) {
            addCriterion("coin_symbol not in", values, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolBetween(String value1, String value2) {
            addCriterion("coin_symbol between", value1, value2, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCoinSymbolNotBetween(String value1, String value2) {
            addCriterion("coin_symbol not between", value1, value2, "coinSymbol");
            return (Criteria) this;
        }

        public Criteria andCnyPriceIsNull() {
            addCriterion("cny_price is null");
            return (Criteria) this;
        }

        public Criteria andCnyPriceIsNotNull() {
            addCriterion("cny_price is not null");
            return (Criteria) this;
        }

        public Criteria andCnyPriceEqualTo(String value) {
            addCriterion("cny_price =", value, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceNotEqualTo(String value) {
            addCriterion("cny_price <>", value, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceGreaterThan(String value) {
            addCriterion("cny_price >", value, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceGreaterThanOrEqualTo(String value) {
            addCriterion("cny_price >=", value, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceLessThan(String value) {
            addCriterion("cny_price <", value, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceLessThanOrEqualTo(String value) {
            addCriterion("cny_price <=", value, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceLike(String value) {
            addCriterion("cny_price like", value, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceNotLike(String value) {
            addCriterion("cny_price not like", value, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceIn(List<String> values) {
            addCriterion("cny_price in", values, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceNotIn(List<String> values) {
            addCriterion("cny_price not in", values, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceBetween(String value1, String value2) {
            addCriterion("cny_price between", value1, value2, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andCnyPriceNotBetween(String value1, String value2) {
            addCriterion("cny_price not between", value1, value2, "cnyPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceIsNull() {
            addCriterion("usd_price is null");
            return (Criteria) this;
        }

        public Criteria andUsdPriceIsNotNull() {
            addCriterion("usd_price is not null");
            return (Criteria) this;
        }

        public Criteria andUsdPriceEqualTo(String value) {
            addCriterion("usd_price =", value, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceNotEqualTo(String value) {
            addCriterion("usd_price <>", value, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceGreaterThan(String value) {
            addCriterion("usd_price >", value, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceGreaterThanOrEqualTo(String value) {
            addCriterion("usd_price >=", value, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceLessThan(String value) {
            addCriterion("usd_price <", value, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceLessThanOrEqualTo(String value) {
            addCriterion("usd_price <=", value, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceLike(String value) {
            addCriterion("usd_price like", value, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceNotLike(String value) {
            addCriterion("usd_price not like", value, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceIn(List<String> values) {
            addCriterion("usd_price in", values, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceNotIn(List<String> values) {
            addCriterion("usd_price not in", values, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceBetween(String value1, String value2) {
            addCriterion("usd_price between", value1, value2, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andUsdPriceNotBetween(String value1, String value2) {
            addCriterion("usd_price not between", value1, value2, "usdPrice");
            return (Criteria) this;
        }

        public Criteria andChangePercentIsNull() {
            addCriterion("change_percent is null");
            return (Criteria) this;
        }

        public Criteria andChangePercentIsNotNull() {
            addCriterion("change_percent is not null");
            return (Criteria) this;
        }

        public Criteria andChangePercentEqualTo(String value) {
            addCriterion("change_percent =", value, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentNotEqualTo(String value) {
            addCriterion("change_percent <>", value, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentGreaterThan(String value) {
            addCriterion("change_percent >", value, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentGreaterThanOrEqualTo(String value) {
            addCriterion("change_percent >=", value, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentLessThan(String value) {
            addCriterion("change_percent <", value, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentLessThanOrEqualTo(String value) {
            addCriterion("change_percent <=", value, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentLike(String value) {
            addCriterion("change_percent like", value, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentNotLike(String value) {
            addCriterion("change_percent not like", value, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentIn(List<String> values) {
            addCriterion("change_percent in", values, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentNotIn(List<String> values) {
            addCriterion("change_percent not in", values, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentBetween(String value1, String value2) {
            addCriterion("change_percent between", value1, value2, "changePercent");
            return (Criteria) this;
        }

        public Criteria andChangePercentNotBetween(String value1, String value2) {
            addCriterion("change_percent not between", value1, value2, "changePercent");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpb_instant_price
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hpb_instant_price
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}