/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.example;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class IssueVoteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public IssueVoteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIssueNoIsNull() {
            addCriterion("issue_no is null");
            return (Criteria) this;
        }

        public Criteria andIssueNoIsNotNull() {
            addCriterion("issue_no is not null");
            return (Criteria) this;
        }

        public Criteria andIssueNoEqualTo(String value) {
            addCriterion("issue_no =", value, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoNotEqualTo(String value) {
            addCriterion("issue_no <>", value, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoGreaterThan(String value) {
            addCriterion("issue_no >", value, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoGreaterThanOrEqualTo(String value) {
            addCriterion("issue_no >=", value, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoLessThan(String value) {
            addCriterion("issue_no <", value, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoLessThanOrEqualTo(String value) {
            addCriterion("issue_no <=", value, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoLike(String value) {
            addCriterion("issue_no like", value, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoNotLike(String value) {
            addCriterion("issue_no not like", value, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoIn(List<String> values) {
            addCriterion("issue_no in", values, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoNotIn(List<String> values) {
            addCriterion("issue_no not in", values, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoBetween(String value1, String value2) {
            addCriterion("issue_no between", value1, value2, "issueNo");
            return (Criteria) this;
        }

        public Criteria andIssueNoNotBetween(String value1, String value2) {
            addCriterion("issue_no not between", value1, value2, "issueNo");
            return (Criteria) this;
        }

        public Criteria andVoteStatusIsNull() {
            addCriterion("vote_status is null");
            return (Criteria) this;
        }

        public Criteria andVoteStatusIsNotNull() {
            addCriterion("vote_status is not null");
            return (Criteria) this;
        }

        public Criteria andVoteStatusEqualTo(String value) {
            addCriterion("vote_status =", value, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusNotEqualTo(String value) {
            addCriterion("vote_status <>", value, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusGreaterThan(String value) {
            addCriterion("vote_status >", value, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusGreaterThanOrEqualTo(String value) {
            addCriterion("vote_status >=", value, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusLessThan(String value) {
            addCriterion("vote_status <", value, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusLessThanOrEqualTo(String value) {
            addCriterion("vote_status <=", value, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusLike(String value) {
            addCriterion("vote_status like", value, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusNotLike(String value) {
            addCriterion("vote_status not like", value, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusIn(List<String> values) {
            addCriterion("vote_status in", values, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusNotIn(List<String> values) {
            addCriterion("vote_status not in", values, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusBetween(String value1, String value2) {
            addCriterion("vote_status between", value1, value2, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andVoteStatusNotBetween(String value1, String value2) {
            addCriterion("vote_status not between", value1, value2, "voteStatus");
            return (Criteria) this;
        }

        public Criteria andNameZhIsNull() {
            addCriterion("name_zh is null");
            return (Criteria) this;
        }

        public Criteria andNameZhIsNotNull() {
            addCriterion("name_zh is not null");
            return (Criteria) this;
        }

        public Criteria andNameZhEqualTo(String value) {
            addCriterion("name_zh =", value, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhNotEqualTo(String value) {
            addCriterion("name_zh <>", value, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhGreaterThan(String value) {
            addCriterion("name_zh >", value, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhGreaterThanOrEqualTo(String value) {
            addCriterion("name_zh >=", value, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhLessThan(String value) {
            addCriterion("name_zh <", value, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhLessThanOrEqualTo(String value) {
            addCriterion("name_zh <=", value, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhLike(String value) {
            addCriterion("name_zh like", value, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhNotLike(String value) {
            addCriterion("name_zh not like", value, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhIn(List<String> values) {
            addCriterion("name_zh in", values, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhNotIn(List<String> values) {
            addCriterion("name_zh not in", values, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhBetween(String value1, String value2) {
            addCriterion("name_zh between", value1, value2, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameZhNotBetween(String value1, String value2) {
            addCriterion("name_zh not between", value1, value2, "nameZh");
            return (Criteria) this;
        }

        public Criteria andNameEnIsNull() {
            addCriterion("name_en is null");
            return (Criteria) this;
        }

        public Criteria andNameEnIsNotNull() {
            addCriterion("name_en is not null");
            return (Criteria) this;
        }

        public Criteria andNameEnEqualTo(String value) {
            addCriterion("name_en =", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnNotEqualTo(String value) {
            addCriterion("name_en <>", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnGreaterThan(String value) {
            addCriterion("name_en >", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("name_en >=", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnLessThan(String value) {
            addCriterion("name_en <", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnLessThanOrEqualTo(String value) {
            addCriterion("name_en <=", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnLike(String value) {
            addCriterion("name_en like", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnNotLike(String value) {
            addCriterion("name_en not like", value, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnIn(List<String> values) {
            addCriterion("name_en in", values, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnNotIn(List<String> values) {
            addCriterion("name_en not in", values, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnBetween(String value1, String value2) {
            addCriterion("name_en between", value1, value2, "nameEn");
            return (Criteria) this;
        }

        public Criteria andNameEnNotBetween(String value1, String value2) {
            addCriterion("name_en not between", value1, value2, "nameEn");
            return (Criteria) this;
        }

        public Criteria andDescZhIsNull() {
            addCriterion("desc_zh is null");
            return (Criteria) this;
        }

        public Criteria andDescZhIsNotNull() {
            addCriterion("desc_zh is not null");
            return (Criteria) this;
        }

        public Criteria andDescZhEqualTo(String value) {
            addCriterion("desc_zh =", value, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhNotEqualTo(String value) {
            addCriterion("desc_zh <>", value, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhGreaterThan(String value) {
            addCriterion("desc_zh >", value, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhGreaterThanOrEqualTo(String value) {
            addCriterion("desc_zh >=", value, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhLessThan(String value) {
            addCriterion("desc_zh <", value, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhLessThanOrEqualTo(String value) {
            addCriterion("desc_zh <=", value, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhLike(String value) {
            addCriterion("desc_zh like", value, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhNotLike(String value) {
            addCriterion("desc_zh not like", value, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhIn(List<String> values) {
            addCriterion("desc_zh in", values, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhNotIn(List<String> values) {
            addCriterion("desc_zh not in", values, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhBetween(String value1, String value2) {
            addCriterion("desc_zh between", value1, value2, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescZhNotBetween(String value1, String value2) {
            addCriterion("desc_zh not between", value1, value2, "descZh");
            return (Criteria) this;
        }

        public Criteria andDescEnIsNull() {
            addCriterion("desc_en is null");
            return (Criteria) this;
        }

        public Criteria andDescEnIsNotNull() {
            addCriterion("desc_en is not null");
            return (Criteria) this;
        }

        public Criteria andDescEnEqualTo(String value) {
            addCriterion("desc_en =", value, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnNotEqualTo(String value) {
            addCriterion("desc_en <>", value, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnGreaterThan(String value) {
            addCriterion("desc_en >", value, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnGreaterThanOrEqualTo(String value) {
            addCriterion("desc_en >=", value, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnLessThan(String value) {
            addCriterion("desc_en <", value, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnLessThanOrEqualTo(String value) {
            addCriterion("desc_en <=", value, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnLike(String value) {
            addCriterion("desc_en like", value, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnNotLike(String value) {
            addCriterion("desc_en not like", value, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnIn(List<String> values) {
            addCriterion("desc_en in", values, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnNotIn(List<String> values) {
            addCriterion("desc_en not in", values, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnBetween(String value1, String value2) {
            addCriterion("desc_en between", value1, value2, "descEn");
            return (Criteria) this;
        }

        public Criteria andDescEnNotBetween(String value1, String value2) {
            addCriterion("desc_en not between", value1, value2, "descEn");
            return (Criteria) this;
        }

        public Criteria andValue1ZhIsNull() {
            addCriterion("value1_zh is null");
            return (Criteria) this;
        }

        public Criteria andValue1ZhIsNotNull() {
            addCriterion("value1_zh is not null");
            return (Criteria) this;
        }

        public Criteria andValue1ZhEqualTo(String value) {
            addCriterion("value1_zh =", value, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhNotEqualTo(String value) {
            addCriterion("value1_zh <>", value, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhGreaterThan(String value) {
            addCriterion("value1_zh >", value, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhGreaterThanOrEqualTo(String value) {
            addCriterion("value1_zh >=", value, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhLessThan(String value) {
            addCriterion("value1_zh <", value, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhLessThanOrEqualTo(String value) {
            addCriterion("value1_zh <=", value, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhLike(String value) {
            addCriterion("value1_zh like", value, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhNotLike(String value) {
            addCriterion("value1_zh not like", value, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhIn(List<String> values) {
            addCriterion("value1_zh in", values, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhNotIn(List<String> values) {
            addCriterion("value1_zh not in", values, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhBetween(String value1, String value2) {
            addCriterion("value1_zh between", value1, value2, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue1ZhNotBetween(String value1, String value2) {
            addCriterion("value1_zh not between", value1, value2, "value1Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhIsNull() {
            addCriterion("value2_zh is null");
            return (Criteria) this;
        }

        public Criteria andValue2ZhIsNotNull() {
            addCriterion("value2_zh is not null");
            return (Criteria) this;
        }

        public Criteria andValue2ZhEqualTo(String value) {
            addCriterion("value2_zh =", value, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhNotEqualTo(String value) {
            addCriterion("value2_zh <>", value, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhGreaterThan(String value) {
            addCriterion("value2_zh >", value, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhGreaterThanOrEqualTo(String value) {
            addCriterion("value2_zh >=", value, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhLessThan(String value) {
            addCriterion("value2_zh <", value, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhLessThanOrEqualTo(String value) {
            addCriterion("value2_zh <=", value, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhLike(String value) {
            addCriterion("value2_zh like", value, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhNotLike(String value) {
            addCriterion("value2_zh not like", value, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhIn(List<String> values) {
            addCriterion("value2_zh in", values, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhNotIn(List<String> values) {
            addCriterion("value2_zh not in", values, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhBetween(String value1, String value2) {
            addCriterion("value2_zh between", value1, value2, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue2ZhNotBetween(String value1, String value2) {
            addCriterion("value2_zh not between", value1, value2, "value2Zh");
            return (Criteria) this;
        }

        public Criteria andValue1EnIsNull() {
            addCriterion("value1_en is null");
            return (Criteria) this;
        }

        public Criteria andValue1EnIsNotNull() {
            addCriterion("value1_en is not null");
            return (Criteria) this;
        }

        public Criteria andValue1EnEqualTo(String value) {
            addCriterion("value1_en =", value, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnNotEqualTo(String value) {
            addCriterion("value1_en <>", value, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnGreaterThan(String value) {
            addCriterion("value1_en >", value, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnGreaterThanOrEqualTo(String value) {
            addCriterion("value1_en >=", value, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnLessThan(String value) {
            addCriterion("value1_en <", value, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnLessThanOrEqualTo(String value) {
            addCriterion("value1_en <=", value, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnLike(String value) {
            addCriterion("value1_en like", value, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnNotLike(String value) {
            addCriterion("value1_en not like", value, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnIn(List<String> values) {
            addCriterion("value1_en in", values, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnNotIn(List<String> values) {
            addCriterion("value1_en not in", values, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnBetween(String value1, String value2) {
            addCriterion("value1_en between", value1, value2, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue1EnNotBetween(String value1, String value2) {
            addCriterion("value1_en not between", value1, value2, "value1En");
            return (Criteria) this;
        }

        public Criteria andValue2EnIsNull() {
            addCriterion("value2_en is null");
            return (Criteria) this;
        }

        public Criteria andValue2EnIsNotNull() {
            addCriterion("value2_en is not null");
            return (Criteria) this;
        }

        public Criteria andValue2EnEqualTo(String value) {
            addCriterion("value2_en =", value, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnNotEqualTo(String value) {
            addCriterion("value2_en <>", value, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnGreaterThan(String value) {
            addCriterion("value2_en >", value, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnGreaterThanOrEqualTo(String value) {
            addCriterion("value2_en >=", value, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnLessThan(String value) {
            addCriterion("value2_en <", value, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnLessThanOrEqualTo(String value) {
            addCriterion("value2_en <=", value, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnLike(String value) {
            addCriterion("value2_en like", value, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnNotLike(String value) {
            addCriterion("value2_en not like", value, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnIn(List<String> values) {
            addCriterion("value2_en in", values, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnNotIn(List<String> values) {
            addCriterion("value2_en not in", values, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnBetween(String value1, String value2) {
            addCriterion("value2_en between", value1, value2, "value2En");
            return (Criteria) this;
        }

        public Criteria andValue2EnNotBetween(String value1, String value2) {
            addCriterion("value2_en not between", value1, value2, "value2En");
            return (Criteria) this;
        }

        public Criteria andFloorNumIsNull() {
            addCriterion("floor_num is null");
            return (Criteria) this;
        }

        public Criteria andFloorNumIsNotNull() {
            addCriterion("floor_num is not null");
            return (Criteria) this;
        }

        public Criteria andFloorNumEqualTo(BigDecimal value) {
            addCriterion("floor_num =", value, "floorNum");
            return (Criteria) this;
        }

        public Criteria andFloorNumNotEqualTo(BigDecimal value) {
            addCriterion("floor_num <>", value, "floorNum");
            return (Criteria) this;
        }

        public Criteria andFloorNumGreaterThan(BigDecimal value) {
            addCriterion("floor_num >", value, "floorNum");
            return (Criteria) this;
        }

        public Criteria andFloorNumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("floor_num >=", value, "floorNum");
            return (Criteria) this;
        }

        public Criteria andFloorNumLessThan(BigDecimal value) {
            addCriterion("floor_num <", value, "floorNum");
            return (Criteria) this;
        }

        public Criteria andFloorNumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("floor_num <=", value, "floorNum");
            return (Criteria) this;
        }

        public Criteria andFloorNumIn(List<BigDecimal> values) {
            addCriterion("floor_num in", values, "floorNum");
            return (Criteria) this;
        }

        public Criteria andFloorNumNotIn(List<BigDecimal> values) {
            addCriterion("floor_num not in", values, "floorNum");
            return (Criteria) this;
        }

        public Criteria andFloorNumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("floor_num between", value1, value2, "floorNum");
            return (Criteria) this;
        }

        public Criteria andFloorNumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("floor_num not between", value1, value2, "floorNum");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("begin_time =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("begin_time <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("begin_time >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_time >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("begin_time <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("begin_time <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("begin_time in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("begin_time not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("begin_time between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("begin_time not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andIsVaildIsNull() {
            addCriterion("is_vaild is null");
            return (Criteria) this;
        }

        public Criteria andIsVaildIsNotNull() {
            addCriterion("is_vaild is not null");
            return (Criteria) this;
        }

        public Criteria andIsVaildEqualTo(String value) {
            addCriterion("is_vaild =", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotEqualTo(String value) {
            addCriterion("is_vaild <>", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildGreaterThan(String value) {
            addCriterion("is_vaild >", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildGreaterThanOrEqualTo(String value) {
            addCriterion("is_vaild >=", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLessThan(String value) {
            addCriterion("is_vaild <", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLessThanOrEqualTo(String value) {
            addCriterion("is_vaild <=", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildLike(String value) {
            addCriterion("is_vaild like", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotLike(String value) {
            addCriterion("is_vaild not like", value, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildIn(List<String> values) {
            addCriterion("is_vaild in", values, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotIn(List<String> values) {
            addCriterion("is_vaild not in", values, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildBetween(String value1, String value2) {
            addCriterion("is_vaild between", value1, value2, "isVaild");
            return (Criteria) this;
        }

        public Criteria andIsVaildNotBetween(String value1, String value2) {
            addCriterion("is_vaild not between", value1, value2, "isVaild");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(Date value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(Date value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(Date value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(Date value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<Date> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<Date> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(Date value1, Date value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNull() {
            addCriterion("gmt_modify is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIsNotNull() {
            addCriterion("gmt_modify is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifyEqualTo(Date value) {
            addCriterion("gmt_modify =", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotEqualTo(Date value) {
            addCriterion("gmt_modify <>", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThan(Date value) {
            addCriterion("gmt_modify >", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modify >=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThan(Date value) {
            addCriterion("gmt_modify <", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modify <=", value, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyIn(List<Date> values) {
            addCriterion("gmt_modify in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotIn(List<Date> values) {
            addCriterion("gmt_modify not in", values, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyBetween(Date value1, Date value2) {
            addCriterion("gmt_modify between", value1, value2, "gmtModify");
            return (Criteria) this;
        }

        public Criteria andGmtModifyNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modify not between", value1, value2, "gmtModify");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table issue_vote
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table issue_vote
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}