/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.entity;

import java.util.Date;

public class CoinConfig extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.coin_symbol
     *
     * @mbg.generated
     */
    private String coinSymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.coin_full_name
     *
     * @mbg.generated
     */
    private String coinFullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.icon_url
     *
     * @mbg.generated
     */
    private String iconUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.coin_precision
     *
     * @mbg.generated
     */
    private String coinPrecision;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.contract_addr
     *
     * @mbg.generated
     */
    private String contractAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.coin_type
     *
     * @mbg.generated
     */
    private String coinType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.order_num
     *
     * @mbg.generated
     */
    private Integer orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.price_from
     *
     * @mbg.generated
     */
    private String priceFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.is_show
     *
     * @mbg.generated
     */
    private String isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coin_config.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.id
     *
     * @return the value of coin_config.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.id
     *
     * @param id the value for coin_config.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.coin_symbol
     *
     * @return the value of coin_config.coin_symbol
     *
     * @mbg.generated
     */
    public String getCoinSymbol() {
        return coinSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.coin_symbol
     *
     * @param coinSymbol the value for coin_config.coin_symbol
     *
     * @mbg.generated
     */
    public void setCoinSymbol(String coinSymbol) {
        this.coinSymbol = coinSymbol == null ? null : coinSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.coin_full_name
     *
     * @return the value of coin_config.coin_full_name
     *
     * @mbg.generated
     */
    public String getCoinFullName() {
        return coinFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.coin_full_name
     *
     * @param coinFullName the value for coin_config.coin_full_name
     *
     * @mbg.generated
     */
    public void setCoinFullName(String coinFullName) {
        this.coinFullName = coinFullName == null ? null : coinFullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.icon_url
     *
     * @return the value of coin_config.icon_url
     *
     * @mbg.generated
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.icon_url
     *
     * @param iconUrl the value for coin_config.icon_url
     *
     * @mbg.generated
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl == null ? null : iconUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.coin_precision
     *
     * @return the value of coin_config.coin_precision
     *
     * @mbg.generated
     */
    public String getCoinPrecision() {
        return coinPrecision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.coin_precision
     *
     * @param coinPrecision the value for coin_config.coin_precision
     *
     * @mbg.generated
     */
    public void setCoinPrecision(String coinPrecision) {
        this.coinPrecision = coinPrecision == null ? null : coinPrecision.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.contract_addr
     *
     * @return the value of coin_config.contract_addr
     *
     * @mbg.generated
     */
    public String getContractAddr() {
        return contractAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.contract_addr
     *
     * @param contractAddr the value for coin_config.contract_addr
     *
     * @mbg.generated
     */
    public void setContractAddr(String contractAddr) {
        this.contractAddr = contractAddr == null ? null : contractAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.coin_type
     *
     * @return the value of coin_config.coin_type
     *
     * @mbg.generated
     */
    public String getCoinType() {
        return coinType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.coin_type
     *
     * @param coinType the value for coin_config.coin_type
     *
     * @mbg.generated
     */
    public void setCoinType(String coinType) {
        this.coinType = coinType == null ? null : coinType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.order_num
     *
     * @return the value of coin_config.order_num
     *
     * @mbg.generated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.order_num
     *
     * @param orderNum the value for coin_config.order_num
     *
     * @mbg.generated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.price_from
     *
     * @return the value of coin_config.price_from
     *
     * @mbg.generated
     */
    public String getPriceFrom() {
        return priceFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.price_from
     *
     * @param priceFrom the value for coin_config.price_from
     *
     * @mbg.generated
     */
    public void setPriceFrom(String priceFrom) {
        this.priceFrom = priceFrom == null ? null : priceFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.status
     *
     * @return the value of coin_config.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.status
     *
     * @param status the value for coin_config.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.is_show
     *
     * @return the value of coin_config.is_show
     *
     * @mbg.generated
     */
    public String getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.is_show
     *
     * @param isShow the value for coin_config.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(String isShow) {
        this.isShow = isShow == null ? null : isShow.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.gmt_create
     *
     * @return the value of coin_config.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.gmt_create
     *
     * @param gmtCreate the value for coin_config.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coin_config.gmt_modify
     *
     * @return the value of coin_config.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coin_config.gmt_modify
     *
     * @param gmtModify the value for coin_config.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CoinConfig other = (CoinConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCoinSymbol() == null ? other.getCoinSymbol() == null : this.getCoinSymbol().equals(other.getCoinSymbol()))
            && (this.getCoinFullName() == null ? other.getCoinFullName() == null : this.getCoinFullName().equals(other.getCoinFullName()))
            && (this.getIconUrl() == null ? other.getIconUrl() == null : this.getIconUrl().equals(other.getIconUrl()))
            && (this.getCoinPrecision() == null ? other.getCoinPrecision() == null : this.getCoinPrecision().equals(other.getCoinPrecision()))
            && (this.getContractAddr() == null ? other.getContractAddr() == null : this.getContractAddr().equals(other.getContractAddr()))
            && (this.getCoinType() == null ? other.getCoinType() == null : this.getCoinType().equals(other.getCoinType()))
            && (this.getOrderNum() == null ? other.getOrderNum() == null : this.getOrderNum().equals(other.getOrderNum()))
            && (this.getPriceFrom() == null ? other.getPriceFrom() == null : this.getPriceFrom().equals(other.getPriceFrom()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getIsShow() == null ? other.getIsShow() == null : this.getIsShow().equals(other.getIsShow()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coin_config
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCoinSymbol() == null) ? 0 : getCoinSymbol().hashCode());
        result = prime * result + ((getCoinFullName() == null) ? 0 : getCoinFullName().hashCode());
        result = prime * result + ((getIconUrl() == null) ? 0 : getIconUrl().hashCode());
        result = prime * result + ((getCoinPrecision() == null) ? 0 : getCoinPrecision().hashCode());
        result = prime * result + ((getContractAddr() == null) ? 0 : getContractAddr().hashCode());
        result = prime * result + ((getCoinType() == null) ? 0 : getCoinType().hashCode());
        result = prime * result + ((getOrderNum() == null) ? 0 : getOrderNum().hashCode());
        result = prime * result + ((getPriceFrom() == null) ? 0 : getPriceFrom().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getIsShow() == null) ? 0 : getIsShow().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        return result;
    }
}