package com.hpb.bc.entity;

import java.math.BigDecimal;
import java.util.Date;

public class IssueVoteDetail extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_vote_detail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_vote_detail.issue_no
     *
     * @mbg.generated
     */
    private String issueNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_vote_detail.option_key
     *
     * @mbg.generated
     */
    private String optionKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_vote_detail.option_menu
     *
     * @mbg.generated
     */
    private String optionMenu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_vote_detail.vote_addr
     *
     * @mbg.generated
     */
    private String voteAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_vote_detail.vote_num
     *
     * @mbg.generated
     */
    private BigDecimal voteNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_vote_detail.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_vote_detail.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_vote_detail.id
     *
     * @return the value of issue_vote_detail.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_vote_detail.id
     *
     * @param id the value for issue_vote_detail.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_vote_detail.issue_no
     *
     * @return the value of issue_vote_detail.issue_no
     *
     * @mbg.generated
     */
    public String getIssueNo() {
        return issueNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_vote_detail.issue_no
     *
     * @param issueNo the value for issue_vote_detail.issue_no
     *
     * @mbg.generated
     */
    public void setIssueNo(String issueNo) {
        this.issueNo = issueNo == null ? null : issueNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_vote_detail.option_key
     *
     * @return the value of issue_vote_detail.option_key
     *
     * @mbg.generated
     */
    public String getOptionKey() {
        return optionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_vote_detail.option_key
     *
     * @param optionKey the value for issue_vote_detail.option_key
     *
     * @mbg.generated
     */
    public void setOptionKey(String optionKey) {
        this.optionKey = optionKey == null ? null : optionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_vote_detail.option_menu
     *
     * @return the value of issue_vote_detail.option_menu
     *
     * @mbg.generated
     */
    public String getOptionMenu() {
        return optionMenu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_vote_detail.option_menu
     *
     * @param optionMenu the value for issue_vote_detail.option_menu
     *
     * @mbg.generated
     */
    public void setOptionMenu(String optionMenu) {
        this.optionMenu = optionMenu == null ? null : optionMenu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_vote_detail.vote_addr
     *
     * @return the value of issue_vote_detail.vote_addr
     *
     * @mbg.generated
     */
    public String getVoteAddr() {
        return voteAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_vote_detail.vote_addr
     *
     * @param voteAddr the value for issue_vote_detail.vote_addr
     *
     * @mbg.generated
     */
    public void setVoteAddr(String voteAddr) {
        this.voteAddr = voteAddr == null ? null : voteAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_vote_detail.vote_num
     *
     * @return the value of issue_vote_detail.vote_num
     *
     * @mbg.generated
     */
    public BigDecimal getVoteNum() {
        return voteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_vote_detail.vote_num
     *
     * @param voteNum the value for issue_vote_detail.vote_num
     *
     * @mbg.generated
     */
    public void setVoteNum(BigDecimal voteNum) {
        this.voteNum = voteNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_vote_detail.gmt_create
     *
     * @return the value of issue_vote_detail.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_vote_detail.gmt_create
     *
     * @param gmtCreate the value for issue_vote_detail.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_vote_detail.gmt_modify
     *
     * @return the value of issue_vote_detail.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_vote_detail.gmt_modify
     *
     * @param gmtModify the value for issue_vote_detail.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        IssueVoteDetail other = (IssueVoteDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIssueNo() == null ? other.getIssueNo() == null : this.getIssueNo().equals(other.getIssueNo()))
            && (this.getOptionKey() == null ? other.getOptionKey() == null : this.getOptionKey().equals(other.getOptionKey()))
            && (this.getOptionMenu() == null ? other.getOptionMenu() == null : this.getOptionMenu().equals(other.getOptionMenu()))
            && (this.getVoteAddr() == null ? other.getVoteAddr() == null : this.getVoteAddr().equals(other.getVoteAddr()))
            && (this.getVoteNum() == null ? other.getVoteNum() == null : this.getVoteNum().equals(other.getVoteNum()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_vote_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIssueNo() == null) ? 0 : getIssueNo().hashCode());
        result = prime * result + ((getOptionKey() == null) ? 0 : getOptionKey().hashCode());
        result = prime * result + ((getOptionMenu() == null) ? 0 : getOptionMenu().hashCode());
        result = prime * result + ((getVoteAddr() == null) ? 0 : getVoteAddr().hashCode());
        result = prime * result + ((getVoteNum() == null) ? 0 : getVoteNum().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        return result;
    }
}