package com.hpb.bc.entity;

public class ParamInfo extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_info.param_id
     *
     * @mbg.generated
     */
    private String paramId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_info.gas_limit
     *
     * @mbg.generated
     */
    private String gasLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_info.gas_price
     *
     * @mbg.generated
     */
    private String gasPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_info.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_info.param_id
     *
     * @return the value of param_info.param_id
     *
     * @mbg.generated
     */
    public String getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_info.param_id
     *
     * @param paramId the value for param_info.param_id
     *
     * @mbg.generated
     */
    public void setParamId(String paramId) {
        this.paramId = paramId == null ? null : paramId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_info.gas_limit
     *
     * @return the value of param_info.gas_limit
     *
     * @mbg.generated
     */
    public String getGasLimit() {
        return gasLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_info.gas_limit
     *
     * @param gasLimit the value for param_info.gas_limit
     *
     * @mbg.generated
     */
    public void setGasLimit(String gasLimit) {
        this.gasLimit = gasLimit == null ? null : gasLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_info.gas_price
     *
     * @return the value of param_info.gas_price
     *
     * @mbg.generated
     */
    public String getGasPrice() {
        return gasPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_info.gas_price
     *
     * @param gasPrice the value for param_info.gas_price
     *
     * @mbg.generated
     */
    public void setGasPrice(String gasPrice) {
        this.gasPrice = gasPrice == null ? null : gasPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_info.value
     *
     * @return the value of param_info.value
     *
     * @mbg.generated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_info.value
     *
     * @param value the value for param_info.value
     *
     * @mbg.generated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ParamInfo other = (ParamInfo) that;
        return (this.getParamId() == null ? other.getParamId() == null : this.getParamId().equals(other.getParamId()))
            && (this.getGasLimit() == null ? other.getGasLimit() == null : this.getGasLimit().equals(other.getGasLimit()))
            && (this.getGasPrice() == null ? other.getGasPrice() == null : this.getGasPrice().equals(other.getGasPrice()))
            && (this.getValue() == null ? other.getValue() == null : this.getValue().equals(other.getValue()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getParamId() == null) ? 0 : getParamId().hashCode());
        result = prime * result + ((getGasLimit() == null) ? 0 : getGasLimit().hashCode());
        result = prime * result + ((getGasPrice() == null) ? 0 : getGasPrice().hashCode());
        result = prime * result + ((getValue() == null) ? 0 : getValue().hashCode());
        return result;
    }
}