package com.hpb.bc.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RedPacketConfig extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.min_num
     *
     * @mbg.generated
     */
    private Integer minNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.max_num
     *
     * @mbg.generated
     */
    private Integer maxNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.min_per_coin
     *
     * @mbg.generated
     */
    private BigDecimal minPerCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.max_per_coin
     *
     * @mbg.generated
     */
    private BigDecimal maxPerCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.time
     *
     * @mbg.generated
     */
    private Integer time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.multiple
     *
     * @mbg.generated
     */
    private Integer multiple;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.rate
     *
     * @mbg.generated
     */
    private BigDecimal rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.is_vaild
     *
     * @mbg.generated
     */
    private String isVaild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.enter_type
     *
     * @mbg.generated
     */
    private String enterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_config.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.id
     *
     * @return the value of red_packet_config.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.id
     *
     * @param id the value for red_packet_config.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.min_num
     *
     * @return the value of red_packet_config.min_num
     *
     * @mbg.generated
     */
    public Integer getMinNum() {
        return minNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.min_num
     *
     * @param minNum the value for red_packet_config.min_num
     *
     * @mbg.generated
     */
    public void setMinNum(Integer minNum) {
        this.minNum = minNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.max_num
     *
     * @return the value of red_packet_config.max_num
     *
     * @mbg.generated
     */
    public Integer getMaxNum() {
        return maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.max_num
     *
     * @param maxNum the value for red_packet_config.max_num
     *
     * @mbg.generated
     */
    public void setMaxNum(Integer maxNum) {
        this.maxNum = maxNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.min_per_coin
     *
     * @return the value of red_packet_config.min_per_coin
     *
     * @mbg.generated
     */
    public BigDecimal getMinPerCoin() {
        return minPerCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.min_per_coin
     *
     * @param minPerCoin the value for red_packet_config.min_per_coin
     *
     * @mbg.generated
     */
    public void setMinPerCoin(BigDecimal minPerCoin) {
        this.minPerCoin = minPerCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.max_per_coin
     *
     * @return the value of red_packet_config.max_per_coin
     *
     * @mbg.generated
     */
    public BigDecimal getMaxPerCoin() {
        return maxPerCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.max_per_coin
     *
     * @param maxPerCoin the value for red_packet_config.max_per_coin
     *
     * @mbg.generated
     */
    public void setMaxPerCoin(BigDecimal maxPerCoin) {
        this.maxPerCoin = maxPerCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.time
     *
     * @return the value of red_packet_config.time
     *
     * @mbg.generated
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.time
     *
     * @param time the value for red_packet_config.time
     *
     * @mbg.generated
     */
    public void setTime(Integer time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.multiple
     *
     * @return the value of red_packet_config.multiple
     *
     * @mbg.generated
     */
    public Integer getMultiple() {
        return multiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.multiple
     *
     * @param multiple the value for red_packet_config.multiple
     *
     * @mbg.generated
     */
    public void setMultiple(Integer multiple) {
        this.multiple = multiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.rate
     *
     * @return the value of red_packet_config.rate
     *
     * @mbg.generated
     */
    public BigDecimal getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.rate
     *
     * @param rate the value for red_packet_config.rate
     *
     * @mbg.generated
     */
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.is_vaild
     *
     * @return the value of red_packet_config.is_vaild
     *
     * @mbg.generated
     */
    public String getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.is_vaild
     *
     * @param isVaild the value for red_packet_config.is_vaild
     *
     * @mbg.generated
     */
    public void setIsVaild(String isVaild) {
        this.isVaild = isVaild == null ? null : isVaild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.enter_type
     *
     * @return the value of red_packet_config.enter_type
     *
     * @mbg.generated
     */
    public String getEnterType() {
        return enterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.enter_type
     *
     * @param enterType the value for red_packet_config.enter_type
     *
     * @mbg.generated
     */
    public void setEnterType(String enterType) {
        this.enterType = enterType == null ? null : enterType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.gmt_create
     *
     * @return the value of red_packet_config.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.gmt_create
     *
     * @param gmtCreate the value for red_packet_config.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_config.gmt_modify
     *
     * @return the value of red_packet_config.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_config.gmt_modify
     *
     * @param gmtModify the value for red_packet_config.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RedPacketConfig other = (RedPacketConfig) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getMinNum() == null ? other.getMinNum() == null : this.getMinNum().equals(other.getMinNum()))
            && (this.getMaxNum() == null ? other.getMaxNum() == null : this.getMaxNum().equals(other.getMaxNum()))
            && (this.getMinPerCoin() == null ? other.getMinPerCoin() == null : this.getMinPerCoin().equals(other.getMinPerCoin()))
            && (this.getMaxPerCoin() == null ? other.getMaxPerCoin() == null : this.getMaxPerCoin().equals(other.getMaxPerCoin()))
            && (this.getTime() == null ? other.getTime() == null : this.getTime().equals(other.getTime()))
            && (this.getMultiple() == null ? other.getMultiple() == null : this.getMultiple().equals(other.getMultiple()))
            && (this.getRate() == null ? other.getRate() == null : this.getRate().equals(other.getRate()))
            && (this.getIsVaild() == null ? other.getIsVaild() == null : this.getIsVaild().equals(other.getIsVaild()))
            && (this.getEnterType() == null ? other.getEnterType() == null : this.getEnterType().equals(other.getEnterType()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_config
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getMinNum() == null) ? 0 : getMinNum().hashCode());
        result = prime * result + ((getMaxNum() == null) ? 0 : getMaxNum().hashCode());
        result = prime * result + ((getMinPerCoin() == null) ? 0 : getMinPerCoin().hashCode());
        result = prime * result + ((getMaxPerCoin() == null) ? 0 : getMaxPerCoin().hashCode());
        result = prime * result + ((getTime() == null) ? 0 : getTime().hashCode());
        result = prime * result + ((getMultiple() == null) ? 0 : getMultiple().hashCode());
        result = prime * result + ((getRate() == null) ? 0 : getRate().hashCode());
        result = prime * result + ((getIsVaild() == null) ? 0 : getIsVaild().hashCode());
        result = prime * result + ((getEnterType() == null) ? 0 : getEnterType().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        return result;
    }
}