package com.hpb.bc.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RedPacket extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.red_packet_no
     *
     * @mbg.generated
     */
    private String redPacketNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.is_over
     *
     * @mbg.generated
     */
    private String isOver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.tx_hash
     *
     * @mbg.generated
     */
    private String txHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.coin_symbol
     *
     * @mbg.generated
     */
    private String coinSymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.from_addr
     *
     * @mbg.generated
     */
    private String fromAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.total_num
     *
     * @mbg.generated
     */
    private Integer totalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.red_packet_type
     *
     * @mbg.generated
     */
    private String redPacketType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.enter_type
     *
     * @mbg.generated
     */
    private String enterType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.total_coin
     *
     * @mbg.generated
     */
    private String totalCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.total_cny
     *
     * @mbg.generated
     */
    private BigDecimal totalCny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.total_usd
     *
     * @mbg.generated
     */
    private BigDecimal totalUsd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.cny_price
     *
     * @mbg.generated
     */
    private BigDecimal cnyPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.miner_fee
     *
     * @mbg.generated
     */
    private String minerFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.is_over_time
     *
     * @mbg.generated
     */
    private String isOverTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.title_en
     *
     * @mbg.generated
     */
    private String titleEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.duration_time
     *
     * @mbg.generated
     */
    private Long durationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    private int usedNum;
    private int refundNum;

    public int getUsedNum() {
        return usedNum;
    }

    public void setUsedNum(int usedNum) {
        this.usedNum = usedNum;
    }

    public int getRefundNum() {
        return refundNum;
    }

    public void setRefundNum(int refundNum) {
        this.refundNum = refundNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.id
     *
     * @return the value of red_packet.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.id
     *
     * @param id the value for red_packet.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.red_packet_no
     *
     * @return the value of red_packet.red_packet_no
     *
     * @mbg.generated
     */
    public String getRedPacketNo() {
        return redPacketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.red_packet_no
     *
     * @param redPacketNo the value for red_packet.red_packet_no
     *
     * @mbg.generated
     */
    public void setRedPacketNo(String redPacketNo) {
        this.redPacketNo = redPacketNo == null ? null : redPacketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.is_over
     *
     * @return the value of red_packet.is_over
     *
     * @mbg.generated
     */
    public String getIsOver() {
        return isOver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.is_over
     *
     * @param isOver the value for red_packet.is_over
     *
     * @mbg.generated
     */
    public void setIsOver(String isOver) {
        this.isOver = isOver == null ? null : isOver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.tx_hash
     *
     * @return the value of red_packet.tx_hash
     *
     * @mbg.generated
     */
    public String getTxHash() {
        return txHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.tx_hash
     *
     * @param txHash the value for red_packet.tx_hash
     *
     * @mbg.generated
     */
    public void setTxHash(String txHash) {
        this.txHash = txHash == null ? null : txHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.status
     *
     * @return the value of red_packet.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.status
     *
     * @param status the value for red_packet.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.coin_symbol
     *
     * @return the value of red_packet.coin_symbol
     *
     * @mbg.generated
     */
    public String getCoinSymbol() {
        return coinSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.coin_symbol
     *
     * @param coinSymbol the value for red_packet.coin_symbol
     *
     * @mbg.generated
     */
    public void setCoinSymbol(String coinSymbol) {
        this.coinSymbol = coinSymbol == null ? null : coinSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.from_addr
     *
     * @return the value of red_packet.from_addr
     *
     * @mbg.generated
     */
    public String getFromAddr() {
        return fromAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.from_addr
     *
     * @param fromAddr the value for red_packet.from_addr
     *
     * @mbg.generated
     */
    public void setFromAddr(String fromAddr) {
        this.fromAddr = fromAddr == null ? null : fromAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.total_num
     *
     * @return the value of red_packet.total_num
     *
     * @mbg.generated
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.total_num
     *
     * @param totalNum the value for red_packet.total_num
     *
     * @mbg.generated
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.red_packet_type
     *
     * @return the value of red_packet.red_packet_type
     *
     * @mbg.generated
     */
    public String getRedPacketType() {
        return redPacketType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.red_packet_type
     *
     * @param redPacketType the value for red_packet.red_packet_type
     *
     * @mbg.generated
     */
    public void setRedPacketType(String redPacketType) {
        this.redPacketType = redPacketType == null ? null : redPacketType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.enter_type
     *
     * @return the value of red_packet.enter_type
     *
     * @mbg.generated
     */
    public String getEnterType() {
        return enterType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.enter_type
     *
     * @param enterType the value for red_packet.enter_type
     *
     * @mbg.generated
     */
    public void setEnterType(String enterType) {
        this.enterType = enterType == null ? null : enterType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.total_coin
     *
     * @return the value of red_packet.total_coin
     *
     * @mbg.generated
     */
    public String getTotalCoin() {
        return totalCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.total_coin
     *
     * @param totalCoin the value for red_packet.total_coin
     *
     * @mbg.generated
     */
    public void setTotalCoin(String totalCoin) {
        this.totalCoin = totalCoin == null ? null : totalCoin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.total_cny
     *
     * @return the value of red_packet.total_cny
     *
     * @mbg.generated
     */
    public BigDecimal getTotalCny() {
        return totalCny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.total_cny
     *
     * @param totalCny the value for red_packet.total_cny
     *
     * @mbg.generated
     */
    public void setTotalCny(BigDecimal totalCny) {
        this.totalCny = totalCny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.total_usd
     *
     * @return the value of red_packet.total_usd
     *
     * @mbg.generated
     */
    public BigDecimal getTotalUsd() {
        return totalUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.total_usd
     *
     * @param totalUsd the value for red_packet.total_usd
     *
     * @mbg.generated
     */
    public void setTotalUsd(BigDecimal totalUsd) {
        this.totalUsd = totalUsd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.cny_price
     *
     * @return the value of red_packet.cny_price
     *
     * @mbg.generated
     */
    public BigDecimal getCnyPrice() {
        return cnyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.cny_price
     *
     * @param cnyPrice the value for red_packet.cny_price
     *
     * @mbg.generated
     */
    public void setCnyPrice(BigDecimal cnyPrice) {
        this.cnyPrice = cnyPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.miner_fee
     *
     * @return the value of red_packet.miner_fee
     *
     * @mbg.generated
     */
    public String getMinerFee() {
        return minerFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.miner_fee
     *
     * @param minerFee the value for red_packet.miner_fee
     *
     * @mbg.generated
     */
    public void setMinerFee(String minerFee) {
        this.minerFee = minerFee == null ? null : minerFee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.is_over_time
     *
     * @return the value of red_packet.is_over_time
     *
     * @mbg.generated
     */
    public String getIsOverTime() {
        return isOverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.is_over_time
     *
     * @param isOverTime the value for red_packet.is_over_time
     *
     * @mbg.generated
     */
    public void setIsOverTime(String isOverTime) {
        this.isOverTime = isOverTime == null ? null : isOverTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.title
     *
     * @return the value of red_packet.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.title
     *
     * @param title the value for red_packet.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.title_en
     *
     * @return the value of red_packet.title_en
     *
     * @mbg.generated
     */
    public String getTitleEn() {
        return titleEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.title_en
     *
     * @param titleEn the value for red_packet.title_en
     *
     * @mbg.generated
     */
    public void setTitleEn(String titleEn) {
        this.titleEn = titleEn == null ? null : titleEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.start_time
     *
     * @return the value of red_packet.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.start_time
     *
     * @param startTime the value for red_packet.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.end_time
     *
     * @return the value of red_packet.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.end_time
     *
     * @param endTime the value for red_packet.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.duration_time
     *
     * @return the value of red_packet.duration_time
     *
     * @mbg.generated
     */
    public Long getDurationTime() {
        return durationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.duration_time
     *
     * @param durationTime the value for red_packet.duration_time
     *
     * @mbg.generated
     */
    public void setDurationTime(Long durationTime) {
        this.durationTime = durationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.gmt_create
     *
     * @return the value of red_packet.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.gmt_create
     *
     * @param gmtCreate the value for red_packet.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet.gmt_modify
     *
     * @return the value of red_packet.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet.gmt_modify
     *
     * @param gmtModify the value for red_packet.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RedPacket other = (RedPacket) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRedPacketNo() == null ? other.getRedPacketNo() == null : this.getRedPacketNo().equals(other.getRedPacketNo()))
            && (this.getIsOver() == null ? other.getIsOver() == null : this.getIsOver().equals(other.getIsOver()))
            && (this.getTxHash() == null ? other.getTxHash() == null : this.getTxHash().equals(other.getTxHash()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCoinSymbol() == null ? other.getCoinSymbol() == null : this.getCoinSymbol().equals(other.getCoinSymbol()))
            && (this.getFromAddr() == null ? other.getFromAddr() == null : this.getFromAddr().equals(other.getFromAddr()))
            && (this.getTotalNum() == null ? other.getTotalNum() == null : this.getTotalNum().equals(other.getTotalNum()))
            && (this.getRedPacketType() == null ? other.getRedPacketType() == null : this.getRedPacketType().equals(other.getRedPacketType()))
            && (this.getEnterType() == null ? other.getEnterType() == null : this.getEnterType().equals(other.getEnterType()))
            && (this.getTotalCoin() == null ? other.getTotalCoin() == null : this.getTotalCoin().equals(other.getTotalCoin()))
            && (this.getTotalCny() == null ? other.getTotalCny() == null : this.getTotalCny().equals(other.getTotalCny()))
            && (this.getTotalUsd() == null ? other.getTotalUsd() == null : this.getTotalUsd().equals(other.getTotalUsd()))
            && (this.getCnyPrice() == null ? other.getCnyPrice() == null : this.getCnyPrice().equals(other.getCnyPrice()))
            && (this.getMinerFee() == null ? other.getMinerFee() == null : this.getMinerFee().equals(other.getMinerFee()))
            && (this.getIsOverTime() == null ? other.getIsOverTime() == null : this.getIsOverTime().equals(other.getIsOverTime()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getTitleEn() == null ? other.getTitleEn() == null : this.getTitleEn().equals(other.getTitleEn()))
            && (this.getStartTime() == null ? other.getStartTime() == null : this.getStartTime().equals(other.getStartTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getDurationTime() == null ? other.getDurationTime() == null : this.getDurationTime().equals(other.getDurationTime()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRedPacketNo() == null) ? 0 : getRedPacketNo().hashCode());
        result = prime * result + ((getIsOver() == null) ? 0 : getIsOver().hashCode());
        result = prime * result + ((getTxHash() == null) ? 0 : getTxHash().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCoinSymbol() == null) ? 0 : getCoinSymbol().hashCode());
        result = prime * result + ((getFromAddr() == null) ? 0 : getFromAddr().hashCode());
        result = prime * result + ((getTotalNum() == null) ? 0 : getTotalNum().hashCode());
        result = prime * result + ((getRedPacketType() == null) ? 0 : getRedPacketType().hashCode());
        result = prime * result + ((getEnterType() == null) ? 0 : getEnterType().hashCode());
        result = prime * result + ((getTotalCoin() == null) ? 0 : getTotalCoin().hashCode());
        result = prime * result + ((getTotalCny() == null) ? 0 : getTotalCny().hashCode());
        result = prime * result + ((getTotalUsd() == null) ? 0 : getTotalUsd().hashCode());
        result = prime * result + ((getCnyPrice() == null) ? 0 : getCnyPrice().hashCode());
        result = prime * result + ((getMinerFee() == null) ? 0 : getMinerFee().hashCode());
        result = prime * result + ((getIsOverTime() == null) ? 0 : getIsOverTime().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getTitleEn() == null) ? 0 : getTitleEn().hashCode());
        result = prime * result + ((getStartTime() == null) ? 0 : getStartTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getDurationTime() == null) ? 0 : getDurationTime().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        return result;
    }
}