/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.entity;

import java.util.Date;

public class RedPacketUse extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_use.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_use.red_packet_no
     *
     * @mbg.generated
     */
    private String redPacketNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_use.total_num
     *
     * @mbg.generated
     */
    private Integer totalNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_use.used_num
     *
     * @mbg.generated
     */
    private Integer usedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_use.refund_num
     *
     * @mbg.generated
     */
    private Integer refundNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_use.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_use.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_use.id
     *
     * @return the value of red_packet_use.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_use.id
     *
     * @param id the value for red_packet_use.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_use.red_packet_no
     *
     * @return the value of red_packet_use.red_packet_no
     *
     * @mbg.generated
     */
    public String getRedPacketNo() {
        return redPacketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_use.red_packet_no
     *
     * @param redPacketNo the value for red_packet_use.red_packet_no
     *
     * @mbg.generated
     */
    public void setRedPacketNo(String redPacketNo) {
        this.redPacketNo = redPacketNo == null ? null : redPacketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_use.total_num
     *
     * @return the value of red_packet_use.total_num
     *
     * @mbg.generated
     */
    public Integer getTotalNum() {
        return totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_use.total_num
     *
     * @param totalNum the value for red_packet_use.total_num
     *
     * @mbg.generated
     */
    public void setTotalNum(Integer totalNum) {
        this.totalNum = totalNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_use.used_num
     *
     * @return the value of red_packet_use.used_num
     *
     * @mbg.generated
     */
    public Integer getUsedNum() {
        return usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_use.used_num
     *
     * @param usedNum the value for red_packet_use.used_num
     *
     * @mbg.generated
     */
    public void setUsedNum(Integer usedNum) {
        this.usedNum = usedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_use.refund_num
     *
     * @return the value of red_packet_use.refund_num
     *
     * @mbg.generated
     */
    public Integer getRefundNum() {
        return refundNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_use.refund_num
     *
     * @param refundNum the value for red_packet_use.refund_num
     *
     * @mbg.generated
     */
    public void setRefundNum(Integer refundNum) {
        this.refundNum = refundNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_use.gmt_create
     *
     * @return the value of red_packet_use.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_use.gmt_create
     *
     * @param gmtCreate the value for red_packet_use.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_use.gmt_modify
     *
     * @return the value of red_packet_use.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_use.gmt_modify
     *
     * @param gmtModify the value for red_packet_use.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_use
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RedPacketUse other = (RedPacketUse) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRedPacketNo() == null ? other.getRedPacketNo() == null : this.getRedPacketNo().equals(other.getRedPacketNo()))
            && (this.getTotalNum() == null ? other.getTotalNum() == null : this.getTotalNum().equals(other.getTotalNum()))
            && (this.getUsedNum() == null ? other.getUsedNum() == null : this.getUsedNum().equals(other.getUsedNum()))
            && (this.getRefundNum() == null ? other.getRefundNum() == null : this.getRefundNum().equals(other.getRefundNum()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_use
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRedPacketNo() == null) ? 0 : getRedPacketNo().hashCode());
        result = prime * result + ((getTotalNum() == null) ? 0 : getTotalNum().hashCode());
        result = prime * result + ((getUsedNum() == null) ? 0 : getUsedNum().hashCode());
        result = prime * result + ((getRefundNum() == null) ? 0 : getRefundNum().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        return result;
    }
}