/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.entity;

import java.util.Date;

public class RedPacketKey extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_key.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_key.red_packet_no
     *
     * @mbg.generated
     */
    private String redPacketNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_key.is_vaild
     *
     * @mbg.generated
     */
    private String isVaild;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_key.packet_key
     *
     * @mbg.generated
     */
    private String packetKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_key.token_id
     *
     * @mbg.generated
     */
    private Long tokenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_key.token_value
     *
     * @mbg.generated
     */
    private String tokenValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_key.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column red_packet_key.gmt_modify
     *
     * @mbg.generated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_key.id
     *
     * @return the value of red_packet_key.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_key.id
     *
     * @param id the value for red_packet_key.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_key.red_packet_no
     *
     * @return the value of red_packet_key.red_packet_no
     *
     * @mbg.generated
     */
    public String getRedPacketNo() {
        return redPacketNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_key.red_packet_no
     *
     * @param redPacketNo the value for red_packet_key.red_packet_no
     *
     * @mbg.generated
     */
    public void setRedPacketNo(String redPacketNo) {
        this.redPacketNo = redPacketNo == null ? null : redPacketNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_key.is_vaild
     *
     * @return the value of red_packet_key.is_vaild
     *
     * @mbg.generated
     */
    public String getIsVaild() {
        return isVaild;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_key.is_vaild
     *
     * @param isVaild the value for red_packet_key.is_vaild
     *
     * @mbg.generated
     */
    public void setIsVaild(String isVaild) {
        this.isVaild = isVaild == null ? null : isVaild.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_key.packet_key
     *
     * @return the value of red_packet_key.packet_key
     *
     * @mbg.generated
     */
    public String getPacketKey() {
        return packetKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_key.packet_key
     *
     * @param packetKey the value for red_packet_key.packet_key
     *
     * @mbg.generated
     */
    public void setPacketKey(String packetKey) {
        this.packetKey = packetKey == null ? null : packetKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_key.token_id
     *
     * @return the value of red_packet_key.token_id
     *
     * @mbg.generated
     */
    public Long getTokenId() {
        return tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_key.token_id
     *
     * @param tokenId the value for red_packet_key.token_id
     *
     * @mbg.generated
     */
    public void setTokenId(Long tokenId) {
        this.tokenId = tokenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_key.token_value
     *
     * @return the value of red_packet_key.token_value
     *
     * @mbg.generated
     */
    public String getTokenValue() {
        return tokenValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_key.token_value
     *
     * @param tokenValue the value for red_packet_key.token_value
     *
     * @mbg.generated
     */
    public void setTokenValue(String tokenValue) {
        this.tokenValue = tokenValue == null ? null : tokenValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_key.gmt_create
     *
     * @return the value of red_packet_key.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_key.gmt_create
     *
     * @param gmtCreate the value for red_packet_key.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column red_packet_key.gmt_modify
     *
     * @return the value of red_packet_key.gmt_modify
     *
     * @mbg.generated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column red_packet_key.gmt_modify
     *
     * @param gmtModify the value for red_packet_key.gmt_modify
     *
     * @mbg.generated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_key
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RedPacketKey other = (RedPacketKey) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
                && (this.getRedPacketNo() == null ? other.getRedPacketNo() == null : this.getRedPacketNo().equals(other.getRedPacketNo()))
                && (this.getIsVaild() == null ? other.getIsVaild() == null : this.getIsVaild().equals(other.getIsVaild()))
                && (this.getPacketKey() == null ? other.getPacketKey() == null : this.getPacketKey().equals(other.getPacketKey()))
                && (this.getTokenId() == null ? other.getTokenId() == null : this.getTokenId().equals(other.getTokenId()))
                && (this.getTokenValue() == null ? other.getTokenValue() == null : this.getTokenValue().equals(other.getTokenValue()))
                && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
                && (this.getGmtModify() == null ? other.getGmtModify() == null : this.getGmtModify().equals(other.getGmtModify()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_key
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRedPacketNo() == null) ? 0 : getRedPacketNo().hashCode());
        result = prime * result + ((getIsVaild() == null) ? 0 : getIsVaild().hashCode());
        result = prime * result + ((getPacketKey() == null) ? 0 : getPacketKey().hashCode());
        result = prime * result + ((getTokenId() == null) ? 0 : getTokenId().hashCode());
        result = prime * result + ((getTokenValue() == null) ? 0 : getTokenValue().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModify() == null) ? 0 : getGmtModify().hashCode());
        return result;
    }
}