/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.entity;

import java.math.BigInteger;

public class TransactionHistoryInfo extends BaseEntity {
    /**
	 *
	 */
	private static final long serialVersionUID = -5820822167417622303L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.transaction_hash
     *
     * @mbg.generated
     */
	private  String tokenURI;

    public String getTokenURI() {
        return tokenURI;
    }

    public void setTokenURI(String tokenURI) {
        this.tokenURI = tokenURI;
    }

    private  String tokenSymbol;

    public String getTokenSymbol() {
        return tokenSymbol;
    }

    public void setTokenSymbol(String tokenSymbol) {
        this.tokenSymbol = tokenSymbol;
    }

    private  String contractAddress;

    public String getContractAddress() {
        return contractAddress;
    }

    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress;
    }

    private String transactionHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.from_account
     *
     * @mbg.generated
     */
    private String fromAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.to_account
     *
     * @mbg.generated
     */
    private String toAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.nonce
     *
     * @mbg.generated
     */
    private Long nonce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.t_value
     *
     * @mbg.generated
     */
    private String tValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.gas
     *
     * @mbg.generated
     */
    private String gas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.gas_price
     *
     * @mbg.generated
     */
    private String gasPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.block_hash
     *
     * @mbg.generated
     */
    private String blockHash;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.block_number
     *
     * @mbg.generated
     */
    private Long blockNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.transaction_index
     *
     * @mbg.generated
     */
    private Long transactionIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.t_timestap
     *
     * @mbg.generated
     */
    private Long tTimestap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.gas_used
     *
     * @mbg.generated
     */
    private String gasUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_history_info.t_input
     *
     * @mbg.generated
     */
    private String tInput;

    private String flag;

    private String tokenId;

    private String tokenType;

    private String decimals;

    public String getDecimals() {
        return decimals;
    }

    public void setDecimals(String decimals) {
        this.decimals = decimals;
    }

    public String getTokenType() {
        return tokenType;
    }

    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }

    public String getTokenId() {
        return tokenId;
    }

    public void setTokenId(String tokenId) {
        this.tokenId = tokenId;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.transaction_hash
     *
     * @return the value of transaction_history_info.transaction_hash
     *
     * @mbg.generated
     */
    public String getTransactionHash() {
        return transactionHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.transaction_hash
     *
     * @param transactionHash the value for transaction_history_info.transaction_hash
     *
     * @mbg.generated
     */
    public void setTransactionHash(String transactionHash) {
        this.transactionHash = transactionHash == null ? null : transactionHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.from_account
     *
     * @return the value of transaction_history_info.from_account
     *
     * @mbg.generated
     */
    public String getFromAccount() {
        return fromAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.from_account
     *
     * @param fromAccount the value for transaction_history_info.from_account
     *
     * @mbg.generated
     */
    public void setFromAccount(String fromAccount) {
        this.fromAccount = fromAccount == null ? null : fromAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.to_account
     *
     * @return the value of transaction_history_info.to_account
     *
     * @mbg.generated
     */
    public String getToAccount() {
        return toAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.to_account
     *
     * @param toAccount the value for transaction_history_info.to_account
     *
     * @mbg.generated
     */
    public void setToAccount(String toAccount) {
        this.toAccount = toAccount == null ? null : toAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.nonce
     *
     * @return the value of transaction_history_info.nonce
     *
     * @mbg.generated
     */
    public Long getNonce() {
        return nonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.nonce
     *
     * @param nonce the value for transaction_history_info.nonce
     *
     * @mbg.generated
     */
    public void setNonce(Long nonce) {
        this.nonce = nonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.t_value
     *
     * @return the value of transaction_history_info.t_value
     *
     * @mbg.generated
     */
    public String gettValue() {
        return tValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.t_value
     *
     * @param tValue the value for transaction_history_info.t_value
     *
     * @mbg.generated
     */
    public void settValue(String tValue) {
        this.tValue = tValue == null ? null : tValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.gas
     *
     * @return the value of transaction_history_info.gas
     *
     * @mbg.generated
     */
    public String getGas() {
        return gas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.gas
     *
     * @param gas the value for transaction_history_info.gas
     *
     * @mbg.generated
     */
    public void setGas(String gas) {
        this.gas = gas == null ? null : gas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.gas_price
     *
     * @return the value of transaction_history_info.gas_price
     *
     * @mbg.generated
     */
    public String getGasPrice() {
        return gasPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.gas_price
     *
     * @param gasPrice the value for transaction_history_info.gas_price
     *
     * @mbg.generated
     */
    public void setGasPrice(String gasPrice) {
        this.gasPrice = gasPrice == null ? null : gasPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.status
     *
     * @return the value of transaction_history_info.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.status
     *
     * @param status the value for transaction_history_info.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.block_hash
     *
     * @return the value of transaction_history_info.block_hash
     *
     * @mbg.generated
     */
    public String getBlockHash() {
        return blockHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.block_hash
     *
     * @param blockHash the value for transaction_history_info.block_hash
     *
     * @mbg.generated
     */
    public void setBlockHash(String blockHash) {
        this.blockHash = blockHash == null ? null : blockHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.block_number
     *
     * @return the value of transaction_history_info.block_number
     *
     * @mbg.generated
     */
    public Long getBlockNumber() {
        return blockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.block_number
     *
     * @param blockNumber the value for transaction_history_info.block_number
     *
     * @mbg.generated
     */
    public void setBlockNumber(Long blockNumber) {
        this.blockNumber = blockNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.transaction_index
     *
     * @return the value of transaction_history_info.transaction_index
     *
     * @mbg.generated
     */
    public Long getTransactionIndex() {
        return transactionIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.transaction_index
     *
     * @param transactionIndex the value for transaction_history_info.transaction_index
     *
     * @mbg.generated
     */
    public void setTransactionIndex(Long transactionIndex) {
        this.transactionIndex = transactionIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.t_timestap
     *
     * @return the value of transaction_history_info.t_timestap
     *
     * @mbg.generated
     */
    public Long gettTimestap() {
        return tTimestap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.t_timestap
     *
     * @param tTimestap the value for transaction_history_info.t_timestap
     *
     * @mbg.generated
     */
    public void settTimestap(Long tTimestap) {
        this.tTimestap = tTimestap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.gas_used
     *
     * @return the value of transaction_history_info.gas_used
     *
     * @mbg.generated
     */
    public String getGasUsed() {
        return gasUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.gas_used
     *
     * @param gasUsed the value for transaction_history_info.gas_used
     *
     * @mbg.generated
     */
    public void setGasUsed(String gasUsed) {
        this.gasUsed = gasUsed == null ? null : gasUsed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.remark
     *
     * @return the value of transaction_history_info.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.remark
     *
     * @param remark the value for transaction_history_info.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_history_info.t_input
     *
     * @return the value of transaction_history_info.t_input
     *
     * @mbg.generated
     */
    public String gettInput() {
        return tInput;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_history_info.t_input
     *
     * @param tInput the value for transaction_history_info.t_input
     *
     * @mbg.generated
     */
    public void settInput(String tInput) {
        this.tInput = tInput == null ? null : tInput.trim();
    }

    public String getActulTxFee() {
    	if(null==gasUsed || "".equals(gas) || null==gasPrice || "".equals(gasPrice)) {
    		return null;
    	}
    	return new BigInteger(gasUsed).multiply(new BigInteger(gasPrice)).toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TransactionHistoryInfo other = (TransactionHistoryInfo) that;
        return (this.getTransactionHash() == null ? other.getTransactionHash() == null : this.getTransactionHash().equals(other.getTransactionHash()))
            && (this.getFromAccount() == null ? other.getFromAccount() == null : this.getFromAccount().equals(other.getFromAccount()))
            && (this.getToAccount() == null ? other.getToAccount() == null : this.getToAccount().equals(other.getToAccount()))
            && (this.getNonce() == null ? other.getNonce() == null : this.getNonce().equals(other.getNonce()))
            && (this.gettValue() == null ? other.gettValue() == null : this.gettValue().equals(other.gettValue()))
            && (this.getGas() == null ? other.getGas() == null : this.getGas().equals(other.getGas()))
            && (this.getGasPrice() == null ? other.getGasPrice() == null : this.getGasPrice().equals(other.getGasPrice()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getBlockHash() == null ? other.getBlockHash() == null : this.getBlockHash().equals(other.getBlockHash()))
            && (this.getBlockNumber() == null ? other.getBlockNumber() == null : this.getBlockNumber().equals(other.getBlockNumber()))
            && (this.getTransactionIndex() == null ? other.getTransactionIndex() == null : this.getTransactionIndex().equals(other.getTransactionIndex()))
            && (this.gettTimestap() == null ? other.gettTimestap() == null : this.gettTimestap().equals(other.gettTimestap()))
            && (this.getGasUsed() == null ? other.getGasUsed() == null : this.getGasUsed().equals(other.getGasUsed()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.gettInput() == null ? other.gettInput() == null : this.gettInput().equals(other.gettInput()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTransactionHash() == null) ? 0 : getTransactionHash().hashCode());
        result = prime * result + ((getFromAccount() == null) ? 0 : getFromAccount().hashCode());
        result = prime * result + ((getToAccount() == null) ? 0 : getToAccount().hashCode());
        result = prime * result + ((getNonce() == null) ? 0 : getNonce().hashCode());
        result = prime * result + ((gettValue() == null) ? 0 : gettValue().hashCode());
        result = prime * result + ((getGas() == null) ? 0 : getGas().hashCode());
        result = prime * result + ((getGasPrice() == null) ? 0 : getGasPrice().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getBlockHash() == null) ? 0 : getBlockHash().hashCode());
        result = prime * result + ((getBlockNumber() == null) ? 0 : getBlockNumber().hashCode());
        result = prime * result + ((getTransactionIndex() == null) ? 0 : getTransactionIndex().hashCode());
        result = prime * result + ((gettTimestap() == null) ? 0 : gettTimestap().hashCode());
        result = prime * result + ((getGasUsed() == null) ? 0 : getGasUsed().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((gettInput() == null) ? 0 : gettInput().hashCode());
        return result;
    }
}
