/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.cms.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hpb.bc.entity.HpbDataDic;
import com.hpb.bc.example.HpbDataDicExample;

public interface HpbDataDicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    long countByExample(HpbDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    int deleteByExample(HpbDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    int insert(HpbDataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    int insertSelective(HpbDataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    List<HpbDataDic> selectByExample(HpbDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    HpbDataDic selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HpbDataDic record, @Param("example") HpbDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HpbDataDic record, @Param("example") HpbDataDicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HpbDataDic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hpb_data_dic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HpbDataDic record);
}