/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.token.mapper;


import com.hpb.bc.entity.ContractErcStandardInfo;
import com.hpb.bc.example.ContractErcStandardInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ContractErcStandardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    long countByExample(ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int deleteByExample(ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int insert(ContractErcStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int insertSelective(ContractErcStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    List<ContractErcStandardInfo> selectByExample(ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    ContractErcStandardInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContractErcStandardInfo record, @Param("example") ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContractErcStandardInfo record, @Param("example") ContractErcStandardInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ContractErcStandardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contract_erc_standard_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ContractErcStandardInfo record);
}