/*
 * Copyright 2020 HPB Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.hpb.bc.chain.mapper;

import com.hpb.bc.entity.TransactionHistoryInfo;
import com.hpb.bc.example.TransactionHistoryInfoExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TransactionHistoryInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    long countByExample(TransactionHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int deleteByExample(TransactionHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String transactionHash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int insert(TransactionHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int insertSelective(TransactionHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    List<TransactionHistoryInfo> selectByExampleWithBLOBs(TransactionHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    List<TransactionHistoryInfo> selectByExample(TransactionHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    TransactionHistoryInfo selectByPrimaryKey(String transactionHash);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TransactionHistoryInfo record, @Param("example") TransactionHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TransactionHistoryInfo record, @Param("example") TransactionHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TransactionHistoryInfo record, @Param("example") TransactionHistoryInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TransactionHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TransactionHistoryInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transaction_history_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TransactionHistoryInfo record);

	/**
	 * 根据address分页查询发送或接收交易
	 * @param example
	 * @return
	 */
	List<TransactionHistoryInfo> selectTransactionHistoryInfoByPage(Map<String, Object> example);

	/**
	 * 根据address分页查询所有交易,包括发送和接收
	 * @param example
	 * @return
	 */
	List<TransactionHistoryInfo> selectTransactionHistoryInfoByAll(Map<String, Object> example);

	/**
	 * 根据hash查询交易行情
	 * @param example
	 * @return
	 */
	TransactionHistoryInfo selectTransactionHistoryInfoByHash(Map<String, Object> example);
}